### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by sebix** [apertus-open-source-cinema/misc-tools-utilities#3]
Tough some files have a license declaration in their header (GPL-2.0+), most don't have one. I recommend to clarify it with one file in the top directory.

Thanks!

**Comment by BAndiT1983** [comment]
Good idea. Will "steal" it for OpenCine repo also, if you don't mind.

**Comment by sebix** [comment]
> Will "steal" it for OpenCine repo also, if you don't mind.

Please do so.

**Comment by sp-apertus** [comment]
updated to gpl v3

now we just need to update (remove) any file headers that are redundant.
